plugins {
    id 'com.android.application'
}

android {
    namespace 'com.kumar.anya'
    compileSdk 35

    defaultConfig {
        applicationId 'com.kumar.anya'
        minSdk 26
        targetSdk 35
        versionCode 30
        versionName '3.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
